packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
  msw: false
catalog:
  vite: 6.3.5
  vitest: 4.1.9
  vite-plus: latest
overrides:
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
