/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupSelectRoleRouteImport } from './routes/signup/select-role'
import { Route as SignupPatientRouteImport } from './routes/signup/patient'
import { Route as SignupDoctorRouteImport } from './routes/signup/doctor'
import { Route as PatientSettingsRouteImport } from './routes/patient/settings'
import { Route as PatientLoginRouteImport } from './routes/patient/login'
import { Route as PatientLogRouteImport } from './routes/patient/log'
import { Route as PatientHistoryRouteImport } from './routes/patient/history'
import { Route as PatientDashboardRouteImport } from './routes/patient/dashboard'
import { Route as PatientAccessRouteImport } from './routes/patient/access'
import { Route as OnboardingPatientRouteImport } from './routes/onboarding/patient'
import { Route as DoctorPendingRouteImport } from './routes/doctor/pending'
import { Route as DoctorOnboardingRouteImport } from './routes/doctor/onboarding'
import { Route as DoctorLoginRouteImport } from './routes/doctor/login'
import { Route as DoctorDashboardRouteImport } from './routes/doctor/dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSyncRouteImport } from './routes/admin/sync'
import { Route as AdminPendingRouteImport } from './routes/admin/pending'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInviteRouteImport } from './routes/admin/invite'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as SignupDoctorIndexRouteImport } from './routes/signup/doctor/index'
import { Route as OnboardingDoctorIndexRouteImport } from './routes/onboarding/doctor/index'
import { Route as SignupDoctorPendingRouteImport } from './routes/signup/doctor/pending'
import { Route as SignupDoctorAffiliationsRouteImport } from './routes/signup/doctor/affiliations'
import { Route as OnboardingDoctorPendingRouteImport } from './routes/onboarding/doctor/pending'
import { Route as OnboardingDoctorAffiliationsRouteImport } from './routes/onboarding/doctor/affiliations'
import { Route as DoctorPatientsIdRouteImport } from './routes/doctor/patients/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSelectRoleRoute = SignupSelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => SignupRoute,
} as any)
const SignupPatientRoute = SignupPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => SignupRoute,
} as any)
const SignupDoctorRoute = SignupDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => SignupRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientLoginRoute = PatientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientLogRoute = PatientLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientAccessRoute = PatientAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => PatientRouteRoute,
} as any)
const OnboardingPatientRoute = OnboardingPatientRouteImport.update({
  id: '/onboarding/patient',
  path: '/onboarding/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPendingRoute = DoctorPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorOnboardingRoute = DoctorOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorLoginRoute = DoctorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInviteRoute = AdminInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SignupDoctorIndexRoute = SignupDoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupDoctorRoute,
} as any)
const OnboardingDoctorIndexRoute = OnboardingDoctorIndexRouteImport.update({
  id: '/onboarding/doctor/',
  path: '/onboarding/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupDoctorPendingRoute = SignupDoctorPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => SignupDoctorRoute,
} as any)
const SignupDoctorAffiliationsRoute =
  SignupDoctorAffiliationsRouteImport.update({
    id: '/affiliations',
    path: '/affiliations',
    getParentRoute: () => SignupDoctorRoute,
  } as any)
const OnboardingDoctorPendingRoute = OnboardingDoctorPendingRouteImport.update({
  id: '/onboarding/doctor/pending',
  path: '/onboarding/doctor/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDoctorAffiliationsRoute =
  OnboardingDoctorAffiliationsRouteImport.update({
    id: '/onboarding/doctor/affiliations',
    path: '/onboarding/doctor/affiliations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DoctorPatientsIdRoute = DoctorPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => DoctorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/doctor/onboarding': typeof DoctorOnboardingRoute
  '/doctor/pending': typeof DoctorPendingRoute
  '/onboarding/patient': typeof OnboardingPatientRoute
  '/patient/access': typeof PatientAccessRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/log': typeof PatientLogRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/signup/doctor': typeof SignupDoctorRouteWithChildren
  '/signup/patient': typeof SignupPatientRoute
  '/signup/select-role': typeof SignupSelectRoleRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/onboarding/doctor/affiliations': typeof OnboardingDoctorAffiliationsRoute
  '/onboarding/doctor/pending': typeof OnboardingDoctorPendingRoute
  '/signup/doctor/affiliations': typeof SignupDoctorAffiliationsRoute
  '/signup/doctor/pending': typeof SignupDoctorPendingRoute
  '/onboarding/doctor/': typeof OnboardingDoctorIndexRoute
  '/signup/doctor/': typeof SignupDoctorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/doctor/onboarding': typeof DoctorOnboardingRoute
  '/doctor/pending': typeof DoctorPendingRoute
  '/onboarding/patient': typeof OnboardingPatientRoute
  '/patient/access': typeof PatientAccessRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/log': typeof PatientLogRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/signup/patient': typeof SignupPatientRoute
  '/signup/select-role': typeof SignupSelectRoleRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/onboarding/doctor/affiliations': typeof OnboardingDoctorAffiliationsRoute
  '/onboarding/doctor/pending': typeof OnboardingDoctorPendingRoute
  '/signup/doctor/affiliations': typeof SignupDoctorAffiliationsRoute
  '/signup/doctor/pending': typeof SignupDoctorPendingRoute
  '/onboarding/doctor': typeof OnboardingDoctorIndexRoute
  '/signup/doctor': typeof SignupDoctorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invite': typeof AdminInviteRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/login': typeof DoctorLoginRoute
  '/doctor/onboarding': typeof DoctorOnboardingRoute
  '/doctor/pending': typeof DoctorPendingRoute
  '/onboarding/patient': typeof OnboardingPatientRoute
  '/patient/access': typeof PatientAccessRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/log': typeof PatientLogRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/signup/doctor': typeof SignupDoctorRouteWithChildren
  '/signup/patient': typeof SignupPatientRoute
  '/signup/select-role': typeof SignupSelectRoleRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/onboarding/doctor/affiliations': typeof OnboardingDoctorAffiliationsRoute
  '/onboarding/doctor/pending': typeof OnboardingDoctorPendingRoute
  '/signup/doctor/affiliations': typeof SignupDoctorAffiliationsRoute
  '/signup/doctor/pending': typeof SignupDoctorPendingRoute
  '/onboarding/doctor/': typeof OnboardingDoctorIndexRoute
  '/signup/doctor/': typeof SignupDoctorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/auth'
    | '/login'
    | '/signup'
    | '/admin/audit'
    | '/admin/audit-log'
    | '/admin/dashboard'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/pending'
    | '/admin/sync'
    | '/admin/users'
    | '/auth/callback'
    | '/doctor/dashboard'
    | '/doctor/login'
    | '/doctor/onboarding'
    | '/doctor/pending'
    | '/onboarding/patient'
    | '/patient/access'
    | '/patient/dashboard'
    | '/patient/history'
    | '/patient/log'
    | '/patient/login'
    | '/patient/settings'
    | '/signup/doctor'
    | '/signup/patient'
    | '/signup/select-role'
    | '/doctor/patients/$id'
    | '/onboarding/doctor/affiliations'
    | '/onboarding/doctor/pending'
    | '/signup/doctor/affiliations'
    | '/signup/doctor/pending'
    | '/onboarding/doctor/'
    | '/signup/doctor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/auth'
    | '/login'
    | '/signup'
    | '/admin/audit'
    | '/admin/audit-log'
    | '/admin/dashboard'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/pending'
    | '/admin/sync'
    | '/admin/users'
    | '/auth/callback'
    | '/doctor/dashboard'
    | '/doctor/login'
    | '/doctor/onboarding'
    | '/doctor/pending'
    | '/onboarding/patient'
    | '/patient/access'
    | '/patient/dashboard'
    | '/patient/history'
    | '/patient/log'
    | '/patient/login'
    | '/patient/settings'
    | '/signup/patient'
    | '/signup/select-role'
    | '/doctor/patients/$id'
    | '/onboarding/doctor/affiliations'
    | '/onboarding/doctor/pending'
    | '/signup/doctor/affiliations'
    | '/signup/doctor/pending'
    | '/onboarding/doctor'
    | '/signup/doctor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/auth'
    | '/login'
    | '/signup'
    | '/admin/audit'
    | '/admin/audit-log'
    | '/admin/dashboard'
    | '/admin/invite'
    | '/admin/login'
    | '/admin/pending'
    | '/admin/sync'
    | '/admin/users'
    | '/auth/callback'
    | '/doctor/dashboard'
    | '/doctor/login'
    | '/doctor/onboarding'
    | '/doctor/pending'
    | '/onboarding/patient'
    | '/patient/access'
    | '/patient/dashboard'
    | '/patient/history'
    | '/patient/log'
    | '/patient/login'
    | '/patient/settings'
    | '/signup/doctor'
    | '/signup/patient'
    | '/signup/select-role'
    | '/doctor/patients/$id'
    | '/onboarding/doctor/affiliations'
    | '/onboarding/doctor/pending'
    | '/signup/doctor/affiliations'
    | '/signup/doctor/pending'
    | '/onboarding/doctor/'
    | '/signup/doctor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DoctorRouteRoute: typeof DoctorRouteRouteWithChildren
  PatientRouteRoute: typeof PatientRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRouteWithChildren
  OnboardingPatientRoute: typeof OnboardingPatientRoute
  OnboardingDoctorAffiliationsRoute: typeof OnboardingDoctorAffiliationsRoute
  OnboardingDoctorPendingRoute: typeof OnboardingDoctorPendingRoute
  OnboardingDoctorIndexRoute: typeof OnboardingDoctorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/select-role': {
      id: '/signup/select-role'
      path: '/select-role'
      fullPath: '/signup/select-role'
      preLoaderRoute: typeof SignupSelectRoleRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/patient': {
      id: '/signup/patient'
      path: '/patient'
      fullPath: '/signup/patient'
      preLoaderRoute: typeof SignupPatientRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/doctor': {
      id: '/signup/doctor'
      path: '/doctor'
      fullPath: '/signup/doctor'
      preLoaderRoute: typeof SignupDoctorRouteImport
      parentRoute: typeof SignupRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/login': {
      id: '/patient/login'
      path: '/login'
      fullPath: '/patient/login'
      preLoaderRoute: typeof PatientLoginRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/log': {
      id: '/patient/log'
      path: '/log'
      fullPath: '/patient/log'
      preLoaderRoute: typeof PatientLogRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/access': {
      id: '/patient/access'
      path: '/access'
      fullPath: '/patient/access'
      preLoaderRoute: typeof PatientAccessRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/onboarding/patient': {
      id: '/onboarding/patient'
      path: '/onboarding/patient'
      fullPath: '/onboarding/patient'
      preLoaderRoute: typeof OnboardingPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/pending': {
      id: '/doctor/pending'
      path: '/pending'
      fullPath: '/doctor/pending'
      preLoaderRoute: typeof DoctorPendingRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/onboarding': {
      id: '/doctor/onboarding'
      path: '/onboarding'
      fullPath: '/doctor/onboarding'
      preLoaderRoute: typeof DoctorOnboardingRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/login': {
      id: '/doctor/login'
      path: '/login'
      fullPath: '/doctor/login'
      preLoaderRoute: typeof DoctorLoginRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invite': {
      id: '/admin/invite'
      path: '/invite'
      fullPath: '/admin/invite'
      preLoaderRoute: typeof AdminInviteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/signup/doctor/': {
      id: '/signup/doctor/'
      path: '/'
      fullPath: '/signup/doctor/'
      preLoaderRoute: typeof SignupDoctorIndexRouteImport
      parentRoute: typeof SignupDoctorRoute
    }
    '/onboarding/doctor/': {
      id: '/onboarding/doctor/'
      path: '/onboarding/doctor'
      fullPath: '/onboarding/doctor/'
      preLoaderRoute: typeof OnboardingDoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/doctor/pending': {
      id: '/signup/doctor/pending'
      path: '/pending'
      fullPath: '/signup/doctor/pending'
      preLoaderRoute: typeof SignupDoctorPendingRouteImport
      parentRoute: typeof SignupDoctorRoute
    }
    '/signup/doctor/affiliations': {
      id: '/signup/doctor/affiliations'
      path: '/affiliations'
      fullPath: '/signup/doctor/affiliations'
      preLoaderRoute: typeof SignupDoctorAffiliationsRouteImport
      parentRoute: typeof SignupDoctorRoute
    }
    '/onboarding/doctor/pending': {
      id: '/onboarding/doctor/pending'
      path: '/onboarding/doctor/pending'
      fullPath: '/onboarding/doctor/pending'
      preLoaderRoute: typeof OnboardingDoctorPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/doctor/affiliations': {
      id: '/onboarding/doctor/affiliations'
      path: '/onboarding/doctor/affiliations'
      fullPath: '/onboarding/doctor/affiliations'
      preLoaderRoute: typeof OnboardingDoctorAffiliationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/$id': {
      id: '/doctor/patients/$id'
      path: '/patients/$id'
      fullPath: '/doctor/patients/$id'
      preLoaderRoute: typeof DoctorPatientsIdRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInviteRoute: typeof AdminInviteRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPendingRoute: typeof AdminPendingRoute
  AdminSyncRoute: typeof AdminSyncRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInviteRoute: AdminInviteRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPendingRoute: AdminPendingRoute,
  AdminSyncRoute: AdminSyncRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DoctorRouteRouteChildren {
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorLoginRoute: typeof DoctorLoginRoute
  DoctorOnboardingRoute: typeof DoctorOnboardingRoute
  DoctorPendingRoute: typeof DoctorPendingRoute
  DoctorPatientsIdRoute: typeof DoctorPatientsIdRoute
}

const DoctorRouteRouteChildren: DoctorRouteRouteChildren = {
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorLoginRoute: DoctorLoginRoute,
  DoctorOnboardingRoute: DoctorOnboardingRoute,
  DoctorPendingRoute: DoctorPendingRoute,
  DoctorPatientsIdRoute: DoctorPatientsIdRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

interface PatientRouteRouteChildren {
  PatientAccessRoute: typeof PatientAccessRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientLogRoute: typeof PatientLogRoute
  PatientLoginRoute: typeof PatientLoginRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
}

const PatientRouteRouteChildren: PatientRouteRouteChildren = {
  PatientAccessRoute: PatientAccessRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientLogRoute: PatientLogRoute,
  PatientLoginRoute: PatientLoginRoute,
  PatientSettingsRoute: PatientSettingsRoute,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SignupDoctorRouteChildren {
  SignupDoctorAffiliationsRoute: typeof SignupDoctorAffiliationsRoute
  SignupDoctorPendingRoute: typeof SignupDoctorPendingRoute
  SignupDoctorIndexRoute: typeof SignupDoctorIndexRoute
}

const SignupDoctorRouteChildren: SignupDoctorRouteChildren = {
  SignupDoctorAffiliationsRoute: SignupDoctorAffiliationsRoute,
  SignupDoctorPendingRoute: SignupDoctorPendingRoute,
  SignupDoctorIndexRoute: SignupDoctorIndexRoute,
}

const SignupDoctorRouteWithChildren = SignupDoctorRoute._addFileChildren(
  SignupDoctorRouteChildren,
)

interface SignupRouteChildren {
  SignupDoctorRoute: typeof SignupDoctorRouteWithChildren
  SignupPatientRoute: typeof SignupPatientRoute
  SignupSelectRoleRoute: typeof SignupSelectRoleRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupDoctorRoute: SignupDoctorRouteWithChildren,
  SignupPatientRoute: SignupPatientRoute,
  SignupSelectRoleRoute: SignupSelectRoleRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRouteWithChildren,
  OnboardingPatientRoute: OnboardingPatientRoute,
  OnboardingDoctorAffiliationsRoute: OnboardingDoctorAffiliationsRoute,
  OnboardingDoctorPendingRoute: OnboardingDoctorPendingRoute,
  OnboardingDoctorIndexRoute: OnboardingDoctorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
