/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/profile/role": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Set role for a new user who has no role yet */
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            role: "patient" | "doctor"
            termsAccepted: true
          }
        }
      }
      responses: {
        /** @description Role set */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              role: string
            }
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Role already set */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    trace?: never
  }
  "/profile/complete": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Complete profile after first sign-in */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            firstName: string
            lastName: string
            dateOfBirth?: string
            registrationNumber?: string
            phoneNumber?: string
          }
        }
      }
      responses: {
        /** @description Profile saved */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json":
              | components["schemas"]["Patient"]
              | components["schemas"]["Doctor"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/profile/doctor/affiliations/{affiliationId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Remove a single doctor affiliation */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          affiliationId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Affiliation deleted */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/profile/doctor/affiliations": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List own doctor affiliations */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Own affiliations */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["DoctorAffiliation"][]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    /** Add a doctor institution or private-practice affiliation */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json":
            | {
                /** Format: uuid */
                institutionId: string
                /** Format: uuid */
                departmentId?: string
              }
            | {
                practiceName: string
              }
        }
      }
      responses: {
        /** @description Affiliation created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["DoctorAffiliation"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Duplicate affiliation */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/patients/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get own patient profile */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Patient profile */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Patient"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    /** Delete own account */
    delete: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Account and all associated data deleted */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    options?: never
    head?: never
    /** Update own patient profile */
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            firstName?: string
            lastName?: string
            dateOfBirth?: string
          }
        }
      }
      responses: {
        /** @description Updated patient profile */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Patient"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    trace?: never
  }
  "/patients/me/readings": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get own reading history */
    get: {
      parameters: {
        query?: {
          type?: "glucose" | "blood_pressure"
          from?: string
          limit?: number
          offset?: number | null
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of readings, newest first */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["Reading"][]
              total: number
            }
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    /** Log a new reading (patient) */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json":
            | {
                /** @enum {string} */
                type: "glucose"
                value1: number
                /** @enum {string} */
                unit: "mg/dL" | "mmol/L"
                /** @enum {string} */
                context: "fasted" | "post_meal"
                notes?: string | null
                /** Format: date-time */
                timestamp: string
              }
            | {
                /** @enum {string} */
                type: "blood_pressure"
                value1: number
                value2: number
                /** @enum {string} */
                unit: "mmHg"
                /** @enum {string} */
                context: "morning" | "evening"
                notes?: string | null
                /** Format: date-time */
                timestamp: string
              }
        }
      }
      responses: {
        /** @description Reading created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Reading"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/patients/{patientId}/readings": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log a reading on behalf of a patient (doctor) */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          patientId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json":
            | {
                /** @enum {string} */
                type: "glucose"
                value1: number
                /** @enum {string} */
                unit: "mg/dL" | "mmol/L"
                /** @enum {string} */
                context: "fasted" | "post_meal"
                notes?: string | null
                /** Format: date-time */
                timestamp: string
              }
            | {
                /** @enum {string} */
                type: "blood_pressure"
                value1: number
                value2: number
                /** @enum {string} */
                unit: "mmHg"
                /** @enum {string} */
                context: "morning" | "evening"
                notes?: string | null
                /** Format: date-time */
                timestamp: string
              }
        }
      }
      responses: {
        /** @description Reading created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Reading"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/readings/{readingId}/notes": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Add or edit a note on a reading (doctor) */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          readingId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            notes: string
          }
        }
      }
      responses: {
        /** @description Reading with updated note */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Reading"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    trace?: never
  }
  "/patients/me/grants": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List active access grants */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Active grants */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["AccessGrant"][]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    /** Grant access to a doctor or department */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            grantType: "individual" | "department"
            granteeId: string
          }
        }
      }
      responses: {
        /** @description Grant created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["AccessGrant"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Already exists */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              code: string
              message: string
            }
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/patients/me/grants/{grantId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Revoke an access grant */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          grantId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Grant revoked */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/patients/me/access-log": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** View who has accessed patient records */
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number | null
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Access log entries */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["AccessLogEntry"][]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/search/doctors": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search doctors by name */
    get: {
      parameters: {
        query: {
          q: string
          limit?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Matching doctors */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              id: string
              name: string
              registrationNumber: string
              affiliations: {
                /** @enum {string} */
                type: "institution" | "practice"
                /** Format: uuid */
                institutionId: string | null
                /** Format: uuid */
                departmentId: string | null
                displayName: string
              }[]
            }[]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/institutions": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all institutions with their departments */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description All institutions */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Institution"][]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/doctors/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get own doctor profile */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Doctor profile */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Doctor"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update own doctor profile */
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            firstName?: string
            lastName?: string
            phoneNumber?: string
          }
        }
      }
      responses: {
        /** @description Updated doctor profile */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Doctor"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    trace?: never
  }
  "/doctors/me/patients": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List patients who have granted this doctor access */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Patient list with alert counts */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              patient: components["schemas"]["Patient"]
              unreadAlertCount: number
              /** Format: date-time */
              lastReadingAt: string | null
            }[]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/doctors/me/patients/{patientId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a patient's full detail */
    get: {
      parameters: {
        query?: {
          from?: string
        }
        header?: never
        path: {
          patientId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Patient detail */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              patient: components["schemas"]["Patient"]
              readings: components["schemas"]["Reading"][]
              thresholds: components["schemas"]["Thresholds"]
            }
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/doctors/me/patients/{patientId}/thresholds": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get thresholds for a patient */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          patientId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Thresholds */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              thresholds: components["schemas"]["Thresholds"]
              isCustom: boolean
            }
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    /** Set custom alert thresholds for a patient */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          patientId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["Thresholds"]
        }
      }
      responses: {
        /** @description Custom thresholds saved */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Thresholds"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/doctors/me/patients/{patientId}/due-date": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Set or clear the due date for a patient */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          patientId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            dueDate: string | null
          }
        }
      }
      responses: {
        /** @description Due date saved */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              dueDate: string | null
            }
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/invites": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Doctor creates a patient invite link */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            departmentId: string
          }
        }
      }
      responses: {
        /** @description Invite created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Invite"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/invites/{token}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Resolve an invite token */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          token: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Invite details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Invite"]
          }
        }
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Expired */
        410: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/admin/users": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all users */
    get: {
      parameters: {
        query?: {
          role?: "patient" | "doctor" | "admin"
          status?: "active" | "suspended"
          limit?: number
          offset?: number | null
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description All users */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: (
                | components["schemas"]["Patient"]
                | components["schemas"]["Doctor"]
              )[]
              total: number
            }
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/admin/users/{userId}/status": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Suspend or reactivate a user account */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          userId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            status: "active" | "suspended"
          }
        }
      }
      responses: {
        /** @description Updated user */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json":
              | components["schemas"]["Patient"]
              | components["schemas"]["Doctor"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    trace?: never
  }
  "/admin/invites": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Admin sends an invite to a patient or doctor */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string
            /** @enum {string} */
            role: "patient" | "doctor"
            name?: string
          }
        }
      }
      responses: {
        /** @description Invite sent */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/admin/audit-log": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get platform audit log */
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number | null
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Audit log entries, newest first */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": {
              data: components["schemas"]["AuditLogEntry"][]
              total: number
            }
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/preferences": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user preferences */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description User preferences */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["UserPreferences"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update user preferences */
    patch: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": {
            /** @enum {string} */
            glucoseUnit: "mg/dL" | "mmol/L"
          }
        }
      }
      responses: {
        /** @description Updated preferences */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["UserPreferences"]
          }
        }
        /** @description Missing or invalid session token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Authenticated but insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Resource not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["Error"]
          }
        }
      }
    }
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Error: {
      code: string
      message: string
    }
    Patient: {
      /** Format: uuid */
      id: string
      firstName: string
      lastName: string
      /** Format: email */
      email: string
      dateOfBirth: string
      dueDate: string | null
      avatarUrl: string | null
      /** @enum {string} */
      role: "patient" | "doctor" | "admin"
      /** @enum {string} */
      status: "active" | "suspended"
      /** Format: date-time */
      createdAt: string
    }
    Doctor: {
      /** Format: uuid */
      id: string
      firstName: string
      lastName: string
      /** Format: email */
      email: string
      registrationNumber: string | null
      phoneNumber: string | null
      /** @enum {string} */
      role: "patient" | "doctor" | "admin"
      /** @enum {string} */
      status: "active" | "suspended"
      affiliations: components["schemas"]["DoctorAffiliation"][]
      /** Format: date-time */
      createdAt: string
    }
    DoctorAffiliation: {
      /** Format: uuid */
      id: string
      /** @enum {string} */
      type: "institution" | "practice"
      institution: {
        /** Format: uuid */
        id: string
        name: string
      } | null
      department: {
        /** Format: uuid */
        id: string
        name: string
      } | null
      practiceName: string | null
    }
    Reading: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      patientId: string
      /** Format: uuid */
      loggedById: string
      /** @enum {string} */
      type: "glucose" | "blood_pressure"
      value1: number
      value2: number | null
      unit: string
      /** @enum {string} */
      context: "fasted" | "post_meal" | "morning" | "evening"
      notes: string | null
      /** Format: date-time */
      timestamp: string
      /** @enum {string} */
      severity: "normal" | "high"
      /** Format: date-time */
      createdAt: string
    }
    AccessGrant: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      patientId: string
      /** @enum {string} */
      grantType: "individual" | "department"
      /** Format: uuid */
      granteeId: string
      granteeName: string
      institutionName: string
      registrationNumber: string | null
      /** Format: date-time */
      grantedAt: string
      /** Format: date-time */
      revokedAt: string | null
      hospitalSharingOptions?: components["schemas"]["HospitalSharingOption"][]
    }
    HospitalSharingOption: {
      /** Format: uuid */
      institutionId: string
      /** Format: uuid */
      departmentId: string
      displayName: string
      /** Format: uuid */
      activeDepartmentGrantId: string | null
      /** Format: date-time */
      grantedAt: string | null
    }
    AccessLogEntry: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      doctorId: string
      doctorName: string
      institutionName: string
      /** Format: date-time */
      accessedAt: string
    }
    Institution: {
      /** Format: uuid */
      id: string
      name: string
      /** @enum {string} */
      type: "hospital" | "health_centre" | "private_practice"
      departments: components["schemas"]["Department"][]
    }
    Department: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      institutionId: string
      name: string
    }
    Thresholds: {
      fastingGlucoseHigh: number
      postMealGlucoseHigh: number
      systolicHigh: number
      diastolicHigh: number
    }
    Invite: {
      /** Format: uuid */
      id: string
      token: string
      /** Format: uuid */
      doctorId: string
      doctorName: string
      institutionName: string
      departmentName: string
      /** Format: date-time */
      expiresAt: string
      /** Format: date-time */
      createdAt: string
    }
    AuditLogEntry: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      actorId: string
      actorName: string
      action: string
      /** Format: uuid */
      targetId: string | null
      targetName: string | null
      /** Format: date-time */
      timestamp: string
    }
    UserPreferences: {
      /** @enum {string} */
      glucoseUnit: "mg/dL" | "mmol/L"
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
